//---------------------------------------------------------------------------------------
// Resets positions of robots
//---------------------------------------------------------------------------------------

() 

  [
  Actor.named("RoboChar1").teleport_actor("TargetPoint1")
  Actor.named("RoboChar2").teleport_actor("TargetPoint2")
  Actor.named("RoboChar3").teleport_actor("TargetPoint3")
  ]

